### NumPy (short for Numerical Python)

#### Since lists are a lot like excel spreadsheet columns, lets do some maths with two lists and see what happens

In [1]:
# lets just add these two guys together
xs = [1,2,3,4,5]
ys = [100,200,300,400,500]
xs+ys

[1, 2, 3, 4, 5, 100, 200, 300, 400, 500]

In [2]:
"kind of "+"like"+" strings!"

'kind of like strings!'

In [5]:
# we could do a one liner list comprehension With a new function callez zip - which literally zips up the items in the list
z = [x+y for x, y in zip(xs,ys)]
z

[101, 202, 303, 404, 505]

In [2]:
import numpy as np # Note the as np part means I have given this package a nickname

In [8]:
np.__version__

'1.15.2'

In [9]:
xar = np.array(xs)
yar = np.array(ys)

zar = xar+yar

zar

array([101, 202, 303, 404, 505])

In [10]:
type(zar)

numpy.ndarray

In [13]:
zar[-1]-zar[0:3]

array([404, 303, 202])

In [14]:
zar[-1]-zar[:3]

array([404, 303, 202])

In [15]:
# However, numpy arrays need all of the same data type to be useful

xs = np.array([1,2,'3'])

print('type for item 0', type(xs[0]))
print('type for item 2', type(xs[2]))

type for item 0 <class 'numpy.str_'>
type for item 2 <class 'numpy.str_'>


In [16]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [17]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 53.9 ms


In [18]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 2.32 s


In [19]:
data = np.random.randn(2, 3)

In [20]:
data

array([[-0.83087762,  1.82947488,  0.56880304],
       [ 1.15974219, -0.33781522, -1.04337925]])

In [21]:
data * 10

array([[ -8.30877621,  18.29474884,   5.68803043],
       [ 11.59742194,  -3.37815221, -10.43379252]])

In [22]:
data + data

array([[-1.66175524,  3.65894977,  1.13760609],
       [ 2.31948439, -0.67563044, -2.0867585 ]])

In [23]:
data.shape

(2, 3)

In [24]:
data.dtype

dtype('float64')

In [28]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [37]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
data2x = [[1, 2, 3], [5, 6, 7, 8]]
data2x

[[1, 2, 3], [5, 6, 7, 8]]

In [35]:
data2xar = np.array(data2x)

In [36]:
data2xar

array([list([1, 2, 3]), list([5, 6, 7, 8])], dtype=object)

In [38]:
arr2.ndim

2

In [39]:
arr2.shape

(2, 4)

In [40]:
arr1.dtype

dtype('float64')

In [41]:
arr2.dtype

dtype('int32')

In [42]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [44]:
np.empty((2, 3, 2))

array([[[8.00958208e-312, 2.81617418e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.33664410e+160]],

       [[5.58049445e-091, 1.25669137e-071],
        [2.36721583e+179, 2.14360710e+160],
        [6.48224659e+170, 4.93432906e+257]]])

In [45]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [47]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [48]:
arr1.dtype

dtype('float64')

In [49]:
arr2.dtype

dtype('int32')

In [51]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [52]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [53]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [54]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [55]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [4]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [6]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [8]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [9]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [10]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [11]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [13]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[5]

5

In [15]:
arr[5:8]

array([5, 6, 7])

In [16]:
arr[5:8] = 12

In [17]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [18]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [19]:
arr2d[2]

array([7, 8, 9])

In [20]:
arr2d[0][2]

3

In [21]:
arr2d[0, 2]

3

In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [23]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [24]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
old_values = arr3d[0].copy()

In [26]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [28]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [29]:
arr3d[1, 0]

array([7, 8, 9])

In [30]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [31]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr2d[1, :2]

array([4, 5])

In [33]:
arr2d[:2, 1:] = 0

In [34]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [35]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [36]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [37]:
data

array([[ 1.00494952, -0.14714853,  1.0601433 ,  1.21526339],
       [ 1.39146022,  0.75997018, -0.46190492,  1.29221942],
       [ 0.82162817,  0.47719982,  0.07462209,  0.30730507],
       [-0.43826498,  1.6724893 ,  1.15864975,  0.30433889],
       [ 0.2531382 , -0.90189083, -0.12694327, -1.19102737],
       [-0.33932292,  1.39182712,  0.61831169, -0.70626298],
       [-0.92958262,  1.3397327 ,  1.61650701, -1.16677675]])

In [38]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [39]:
data[names == 'Bob']

array([[ 1.00494952, -0.14714853,  1.0601433 ,  1.21526339],
       [-0.43826498,  1.6724893 ,  1.15864975,  0.30433889]])

In [40]:
data[names == 'Bob', 2:]

array([[1.0601433 , 1.21526339],
       [1.15864975, 0.30433889]])

In [41]:
data[names == 'Bob', 3]

array([1.21526339, 0.30433889])

In [42]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [43]:
data[~(names == 'Bob')]

array([[ 1.39146022,  0.75997018, -0.46190492,  1.29221942],
       [ 0.82162817,  0.47719982,  0.07462209,  0.30730507],
       [ 0.2531382 , -0.90189083, -0.12694327, -1.19102737],
       [-0.33932292,  1.39182712,  0.61831169, -0.70626298],
       [-0.92958262,  1.3397327 ,  1.61650701, -1.16677675]])

In [44]:
cond = names == 'Bob'

In [45]:
data[~cond]

array([[ 1.39146022,  0.75997018, -0.46190492,  1.29221942],
       [ 0.82162817,  0.47719982,  0.07462209,  0.30730507],
       [ 0.2531382 , -0.90189083, -0.12694327, -1.19102737],
       [-0.33932292,  1.39182712,  0.61831169, -0.70626298],
       [-0.92958262,  1.3397327 ,  1.61650701, -1.16677675]])

In [47]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [48]:
data[mask]

array([[ 1.00494952, -0.14714853,  1.0601433 ,  1.21526339],
       [ 0.82162817,  0.47719982,  0.07462209,  0.30730507],
       [-0.43826498,  1.6724893 ,  1.15864975,  0.30433889],
       [ 0.2531382 , -0.90189083, -0.12694327, -1.19102737]])

In [49]:
data[data < 0] = 0

In [50]:
data

array([[1.00494952, 0.        , 1.0601433 , 1.21526339],
       [1.39146022, 0.75997018, 0.        , 1.29221942],
       [0.82162817, 0.47719982, 0.07462209, 0.30730507],
       [0.        , 1.6724893 , 1.15864975, 0.30433889],
       [0.2531382 , 0.        , 0.        , 0.        ],
       [0.        , 1.39182712, 0.61831169, 0.        ],
       [0.        , 1.3397327 , 1.61650701, 0.        ]])

In [51]:
names != 'Joe'

array([ True, False,  True,  True,  True, False, False])

In [52]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.39146022, 0.75997018, 0.        , 1.29221942],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.39182712, 0.61831169, 0.        ],
       [0.        , 1.3397327 , 1.61650701, 0.        ]])

In [53]:
arr = np.empty((8, 4))

In [54]:
for i in range(8):
    arr[i] = i

In [55]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [56]:
arr = np.arange(32).reshape((8, 4))

In [57]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [58]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [59]:
arr = np.arange(15).reshape((3, 5))

In [60]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [62]:
np.dot(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])